=== paulromer12/school_assignments/spring25/csd430/module9/scifi.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns="http://localhost:8080/xml-validate/xsd"
    targetNamespace="http://localhost:8080/xml-validate/xsd"
    elementFormDefault="qualified"
    attributeFormDefault="unqualified">

  <xs:element name="scifi_library">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="title" type="xs:string"/>
              <xs:element name="published" type="xs:gYear"/> <xs:element name="adaptation">
                <xs:complexType>
                  <xs:attribute name="has_movie" type="xs:boolean" use="required"/> </xs:complexType>
              </xs:element>
              <xs:element name="series_length" type="xs:positiveInteger"/> </xs:sequence>
          </xs:complexType>
        </xs:element> 
      </xs:sequence>
    </xs:complexType>
  </xs:element> 
</xs:schema>

=== paulromer12/school_assignments/spring25/csd430/module9/scifi_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="styles.css"?>

<scifi_library xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://localhost:8080/xml-validate/xsd"
               xsi:schemaLocation="http://localhost:8080/xml-validate/xsd scifi.xsd">

  <book>
    <title>Foundation</title>
    <published>1951</published>
    <adaptation has_movie="true"/> <series_length>7</series_length> </book>

  <book>
    <title>Dune</title>
    <published>1965</published>
    <adaptation has_movie="true"/>
    <series_length>6</series_length> </book>

  <book>
    <title>Ready Player One</title>
    <published>2011</published>
    <adaptation has_movie="true"/>
    <series_length>2</series_length> </book>

  <book>
    <title>Ender's Game</title>
    <published>1985</published>
    <adaptation has_movie="true"/>
    <series_length>5</series_length> </book>

    <book>
    <title>Hyperion</title>
    <published>1989</published>
    <adaptation has_movie="false"/>
    <series_length>4</series_length> </book>

</scifi_library>
